# nixpacks.toml en la raíz del repo
[phases.setup]
# Fija Node 20 (Nuxt 3.17 va bien con 20.x)
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --include=optional",
  "npm rebuild oxc-parser --build-from-source || true"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"
